version: '2'
services:
    opencats:
      container_name: opencats_test_web
      image: prooph/nginx:www
      ports:
          - "80:80"
          - "443:443"
      volumes_from:
        - opencatsdata

    php:
      container_name: opencats_test_php
      build: ./php/
      volumes_from:
        - opencatsdata

    opencatsdata:
      container_name: opencats_test_data
      image: busybox
      volumes:
        - ..:/var/www/public
        - ../test/config.php:/var/www/public/config.php
        - ../test/INSTALL_BLOCK:/var/www/public/INSTALL_BLOCK
      command: "true"

    opencatsdb:
      container_name: opencats_test_mariadb
      image: mariadb
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
        - MYSQL_DATABASE=cats_test
      volumes:
        - ../test/data/:/test/data/
        - ../test/data/test.sql:/docker-entrypoint-initdb.d/000_test.sql

    unittestdb:
      image: mariadb
      ports:
        - 3307:3306
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
        - MYSQL_DATABASE=cats_unittests

    selenium:
      container_name: selenium_test
      image: mlespiau/standalone-chrome:chromedriver2.23-1
      ports:
        - 4444
